<a href="https://colab.research.google.com/github/felipedram/tf_developer/blob/main/00_create_and_shuffle_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
tf.__version__

'2.15.0'

## Começar pelo começo

In [5]:
constant_1 = tf.constant(1)  # function
variable_1 = tf.Variable(1)  # Class
constant_1, variable_1

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>)

In [7]:
variable_1.assign(10)
variable_1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

### Criar tensores aleatórios

In [ ]:
tf.random.set_seed(42)  # Global seed. Garante mesma sequência a cada execução do programa.

Mais sobre global vs operation seed em https://www.tensorflow.org/api_docs/python/tf/random/set_seed

#### Distribuição Uniforme

In [12]:
uniform_1 = tf.random.Generator.from_seed(42) # Opeeration-level seed
uniform_1 = uniform_1.uniform((2,5))


uniform_2 = tf.random.Generator.from_seed(42) # Opeeration-level seed
uniform_2 = uniform_2.uniform((2,5))

uniform_1, uniform_2

(<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ],
        [0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ],
        [0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ]],
       dtype=float32)>)

In [15]:
uniform_1 == uniform_2

<tf.Tensor: shape=(2, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [16]:
uniform_3 = tf.random.uniform((2, 5))
uniform_4 = tf.random.uniform((2, 5))

uniform_3, uniform_4

(<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[0.28384602, 0.99616015, 0.44106638, 0.9444777 , 0.41346908],
        [0.39854956, 0.84879243, 0.89907336, 0.53077674, 0.28820622]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[0.63083315, 0.639995  , 0.96908   , 0.89969385, 0.18036759],
        [0.61852896, 0.75754595, 0.32295966, 0.79459894, 0.09791148]],
       dtype=float32)>)

In [17]:
uniform_3 == uniform_4

<tf.Tensor: shape=(2, 5), dtype=bool, numpy=
array([[False, False, False, False, False],
       [False, False, False, False, False]])>

#### Distribuição normal

In [10]:
normal_1 = tf.random.normal((3, 4), seed=42)  # Outra forma de atribuir a operation-level seed
normal_1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

## Shuffle

In [20]:
uniform_shuffled = tf.random.shuffle(uniform_1, seed=42)
uniform_shuffled  # mantém a dimensão original

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ],
       [0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ]],
      dtype=float32)>

In [19]:
normal_shuffled = tf.random.shuffle(normal_1, seed=42)
normal_shuffled  # mantém a dimensão original

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ]],
      dtype=float32)>